cmake_minimum_required(VERSION 3.25)
if(NOT DEFINED SOURCE_DIR OR NOT DEFINED TEST_ROOT)
  message(FATAL_ERROR "Pass SOURCE_DIR and TEST_ROOT")
endif()
string(RANDOM LENGTH 12 _suffix)
set(_work "${TEST_ROOT}/${_suffix}")
file(MAKE_DIRECTORY "${_work}/vcpkg/share/sdl3")
file(WRITE "${_work}/vcpkg/share/sdl3/copyright" "Fixture license\n")
set(CMAKE_CURRENT_SOURCE_DIR "${SOURCE_DIR}")
set(FRAME_EXTRACTOR_VCPKG_PREFIX "${_work}/vcpkg")
set(CMAKE_SYSTEM_NAME Linux)
configure_file("${CMAKE_CURRENT_SOURCE_DIR}/cmake/FixupPortablePackage.cmake.in" "${_work}/fixup.cmake" @ONLY)
set(ENV{DESTDIR} "${_work}/stage")
set(CMAKE_INSTALL_PREFIX "/opt/frame-extractor")
include("${_work}/fixup.cmake")
if(NOT EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/share/frame-extractor/licenses/third-party/sdl3.txt")
  message(FATAL_ERROR "DEB license staging failed")
endif()
set(ENV{DESTDIR} "")
set(CMAKE_INSTALL_PREFIX "${_work}/archive")
include("${_work}/fixup.cmake")
if(NOT EXISTS "${CMAKE_INSTALL_PREFIX}/share/frame-extractor/licenses/third-party/sdl3.txt")
  message(FATAL_ERROR "TGZ license staging failed")
endif()
message(STATUS "DEB and TGZ license staging passed")
file(REMOVE_RECURSE "${_work}")
